table fact_cycle_snapshot
	lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012345

	measure 'Snapshot Pass Rate %' = DIVIDE(SUM('fact_cycle_snapshot'[passed_tests]), SUM('fact_cycle_snapshot'[executed_tests]), 0) * 100
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012346

	measure 'Snapshot Coverage %' = DIVIDE(SUM('fact_cycle_snapshot'[covered_requirements]), SUM('fact_cycle_snapshot'[total_requirements]), 0) * 100
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012347

	measure 'Snapshot Automation Rate %' = DIVIDE(SUM('fact_cycle_snapshot'[automated_executions]), SUM('fact_cycle_snapshot'[executed_tests]), 0) * 100
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012348

	measure 'Snapshot Open Critical Defects' = SUM('fact_cycle_snapshot'[open_critical_defects])
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012349

	column snapshot_sk
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012350
		sourceColumn: snapshot_sk
		isHidden

	column snapshot_date_sk
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012351
		sourceColumn: snapshot_date_sk
		isHidden

	column release_sk
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012352
		sourceColumn: release_sk
		isHidden

	column squad_sk
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012353
		sourceColumn: squad_sk
		isHidden

	column total_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012354
		sourceColumn: total_tests

	column executed_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012355
		sourceColumn: executed_tests

	column passed_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012356
		sourceColumn: passed_tests

	column failed_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012357
		sourceColumn: failed_tests

	column blocked_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012358
		sourceColumn: blocked_tests

	column not_run_tests
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012359
		sourceColumn: not_run_tests

	column automated_executions
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012360
		sourceColumn: automated_executions

	column covered_requirements
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012361
		sourceColumn: covered_requirements

	column total_requirements
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012362
		sourceColumn: total_requirements

	column open_critical_defects
		dataType: int64
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012363
		sourceColumn: open_critical_defects

	column avg_duration_s
		dataType: double
		lineageTag: a7b8c9d0-e1f2-3456-abcd-456789012364
		sourceColumn: avg_duration_s

	partition fact_cycle_snapshot = m
		mode: import
		source =
				let
				    Source = Sql.Database("127.0.0.1,1433", "Reporting_DB"),
				    fact_cycle_snapshot = Source{[Schema="dbo", Item="fact_cycle_snapshot"]}[Data]
				in
				    fact_cycle_snapshot
